<a href="https://colab.research.google.com/github/abijithnv/Learn.py/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [ ]:
import numpy as np
import random
 
matrix=np.random.randint(100,size=(3,3))
print(matrix)

[[94 49 28]
 [ 7  9 10]
 [74 20 70]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [ ]:
import numpy as np
import random
 
array=np.random.randint(100,size=(4,4))
print("4x4 matrix :""\n", array)
newarr=array.reshape(2,8)
print("2x8 matrix :""\n",newarr)
 
ve=np.vstack(newarr)
ho=np.hstack(newarr)
print("vertical Stack:""\n",ve)
print("horizontal Stack:""\n",ho)

4x4 matrix :
 [[10 95 18  9]
 [12 26 86 69]
 [77 53 57 92]
 [86 84 78 70]]
2x8 matrix :
 [[10 95 18  9 12 26 86 69]
 [77 53 57 92 86 84 78 70]]
vertical Stack:
 [[10 95 18  9 12 26 86 69]
 [77 53 57 92 86 84 78 70]]
horizontal Stack:
 [10 95 18  9 12 26 86 69 77 53 57 92 86 84 78 70]
