<a href="https://colab.research.google.com/github/abijithnv/Learn.py/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [ ]:
import numpy as np
 
arr=np.random.randint(10,size=(3,3))
arr2=np.random.randint(10,size=(3,3))
dt=np.dot(arr,arr2)
print("Dot product :\n",dt)
print("Transpose :\n",dt.T)

Dot product :
 [[ 98  60  62]
 [ 49  33  16]
 [122  71  72]]
Transpose :
 [[ 98  49 122]
 [ 60  33  71]
 [ 62  16  72]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [ ]:
import numpy as np
 
arr=np.array([[55,25,15],[30,44,2],[11,45,77]])
print(arr)
det=np.linalg.det(arr)
print ("determinant:\n",det)

[[55 25 15]
 [30 44  2]
 [11 45 77]]
determinant:
 137180.0000000001
