<a href="https://colab.research.google.com/github/abijithnv/Learn.py/blob/main/TASK_17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a DataFrame by passing a random numpy array,with a datetie index and labelled columns.and display its,
     - Head
     - Tail
     - Index 
     - Columns
     - Values
     - statistics


In [ ]:
 
import numpy as np
import pandas as pd
datetie = pd.date_range('2021-08-24',periods=4)
df = pd.DataFrame(np.random.randn(4,4), index=datetie, columns=list('ABCD'))
print("Head:\n", df.head())
print("Tail:\n", df.tail())
print("Index:\n", df.index)
print("Columns:\n", df.columns)
print("Values:\n", df.values)
print("Statistics:\n", df.describe(include='all'))

Head:
                    A         B         C         D
2021-08-24 -0.051121 -1.402887 -0.977190 -0.935997
2021-08-25 -0.282484 -1.027398  0.481119  0.619815
2021-08-26  0.473914 -0.213784 -1.932727  1.015354
2021-08-27  1.629444  1.342472 -0.125122 -0.157583
Tail:
                    A         B         C         D
2021-08-24 -0.051121 -1.402887 -0.977190 -0.935997
2021-08-25 -0.282484 -1.027398  0.481119  0.619815
2021-08-26  0.473914 -0.213784 -1.932727  1.015354
2021-08-27  1.629444  1.342472 -0.125122 -0.157583
Index:
 DatetimeIndex(['2021-08-24', '2021-08-25', '2021-08-26', '2021-08-27'], dtype='datetime64[ns]', freq='D')
Columns:
 Index(['A', 'B', 'C', 'D'], dtype='object')
Values:
 [[-0.05112089 -1.40288662 -0.9771904  -0.93599726]
 [-0.28248436 -1.02739762  0.48111899  0.6198148 ]
 [ 0.47391362 -0.21378396 -1.93272724  1.01535396]
 [ 1.62944391  1.34247176 -0.12512162 -0.15758254]]
Statistics:
               A         B         C         D
count  4.000000  4.000000  4.000000

2. Use the above table and,
      - find transpose of your data.
      - sort the index in the descending order of the date.

In [ ]:
print("Transpose\n", df.transpose())
print("Sorted in Descending Order\n", df.sort_index(ascending=False))

Transpose
    2021-08-24  2021-08-25  2021-08-26  2021-08-27
A   -0.051121   -0.282484    0.473914    1.629444
B   -1.402887   -1.027398   -0.213784    1.342472
C   -0.977190    0.481119   -1.932727   -0.125122
D   -0.935997    0.619815    1.015354   -0.157583
Sorted in Descending Order
                    A         B         C         D
2021-08-27  1.629444  1.342472 -0.125122 -0.157583
2021-08-26  0.473914 -0.213784 -1.932727  1.015354
2021-08-25 -0.282484 -1.027398  0.481119  0.619815
2021-08-24 -0.051121 -1.402887 -0.977190 -0.935997
