<a href="https://colab.research.google.com/github/abijithnv/Learn.py/blob/main/TASK_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a 3x3 array values ranging from 0-8.Find the sum of the elements in this array.

In [1]:
 import numpy as np
 
array=np.arange(0,9)
ar=array.reshape(3,3)
print (np.sum(ar))

36


2. Create a 3x3 array values ranging from 0-8.Find the row sum and column sum of this array.

In [2]:
 import numpy as np
 
array=np.arange(0,9)
ar=array.reshape(3,3)
print("Sum of each column:")
print(np.sum(ar,axis=0))
print("Sum of each row:")
print(np.sum(ar,axis=1))

Sum of each column:
[ 9 12 15]
Sum of each row:
[ 3 12 21]


3. Create a 4x4 array values ranging from 0-15. Now,

    a) Find the mininmum value in the array.
    
    b) Find the maximum value in the array.

    c) Find the mean of the values in the array.

In [3]:
import numpy as np
 
array=np.arange(0,16)
ar=array.reshape(4,4)
 
print("minimum",np.min(ar))
print("maximum",np.max(ar))
print("mean",np.mean(ar))

minimum 0
maximum 15
mean 7.5


4. Create an 10x10 array values ranging from 0-99.And ,

    a) Print the 7th row.
    
    b) Print the rows from 4-8.

    c) Print the value at the index 5,5.

    d) Print the 5th colomn.

    e) Print the columns from 2-5.

In [6]:
import numpy as np
 
array=np.arange(0,100)
ar=array.reshape(10,10)
row = ar[6, :]
print('7th row\n', row)
rows = ar[3:8, :]
print ("row 4 to 8\n",rows)
print("array of index 5,5 =",ar[5,5])
print("5th column ",ar[:,4])
print("column 2 to 5\n",ar[:,1:5])

7th row
 [60 61 62 63 64 65 66 67 68 69]
row 4 to 8
 [[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]]
array of index 5,5 = 55
5th column  [ 4 14 24 34 44 54 64 74 84 94]
column 2 to 5
 [[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]
 [51 52 53 54]
 [61 62 63 64]
 [71 72 73 74]
 [81 82 83 84]
 [91 92 93 94]]
