<a href="https://colab.research.google.com/github/abijithnv/Learn.py/blob/main/TASK_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. For the given ndarray b below, evaluate whether elements in array, b are equal to 'red'.Assign the result to b_bool and print the resultant boolean array.
b = np.array(["blue", "blue", "red", "blue"])

In [2]:
import numpy as np
b = np.array(["blue", "blue", "red", "blue"])
b_bool=(b=="red")
print(b_bool)

[False False  True False]


2. Create two arrays on containing elements from 0-5 and another containing elements from 6-10. Then append this array.

In [3]:
import numpy as np
 
ar=np.array(np.arange(0,6))
ar2=np.array(np.arange(6,11))
array=np.append(ar,ar2)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10]


3. Create a 2x4 array containing values from 0-7 and another 2x4 containing values from 8-15. Now append this with,

  a) axis as 0

  b) axis as 1

In [4]:
import numpy as np
 
ar=np.arange(0,8).reshape(2,4)
ar2=np.arange(8,16).reshape(2,4)
 
axis_0=np.append(ar,ar2,axis=0)
print("axis 1",axis_0)
 
axis_1=np.append(ar,ar2,axis=1)
print("axis 1",axis_1)

axis 1 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
axis 1 [[ 0  1  2  3  8  9 10 11]
 [ 4  5  6  7 12 13 14 15]]
